# Generated by Django 2.2.5 on 2019-09-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.TextField()),
                ('data_de_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=9)),
                ('item_de_doacao', models.CharField(max_length=255)),
                ('data_de_criacao', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
